server:
  port: 8080
  servlet:
    context-path: /bootcampsantander

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://ljdtqmdxtwzjmc:9a443920b98f6daa66049ed8f0c0c3853f2783ee63c6d8caecd118c373db2cc4@ec2-34-230-115-172.compute-1.amazonaws.com:5432/de19s8olsdq3ia
    username: ljdtqmdxtwzjmc
    password: 9a443920b98f6daa66049ed8f0c0c3853f2783ee63c6d8caecd118c373db2cc4
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none


application:
  description: PROJETO CRIADO PARA O BOOTCAMP DIO - SANTANDER

